import Vue from 'vue';
import ValidatedField from './ValidatedField.vue';
import TelInput from './TelInput.vue';
import SlimSelect from './SlimSelect.vue';
import CheckBox from './CheckBox.vue';
import Switcher from './Switcher.vue';
import Radio from './Radio.vue';
import SubmitButton from './SubmitButton.vue';
import DropDown from './DropDown.vue';
import DatePicker from './DatePicker.vue';
import Spinner from './Spinner.vue';
import LangSelector from './LangSelector.vue';
import AmountPercent from './AmountPercent.vue';
import GuestsPrice from './GuestsPrice.vue';
import GuestsPriceMultiple from './GuestsPriceMultiple.vue';

Vue.component(ValidatedField.name, ValidatedField);
Vue.component(TelInput.name, TelInput);
Vue.component(SlimSelect.name, SlimSelect);
Vue.component(CheckBox.name, CheckBox);
Vue.component(Switcher.name, Switcher);
Vue.component(Radio.name, Radio);
Vue.component(SubmitButton.name, SubmitButton);
Vue.component(DropDown.name, DropDown);
Vue.component(DatePicker.name, DatePicker);
Vue.component(Spinner.name, Spinner);
Vue.component(LangSelector.name, LangSelector);
Vue.component(AmountPercent.name, AmountPercent);
Vue.component(GuestsPrice.name, GuestsPrice);
Vue.component(GuestsPriceMultiple.name, GuestsPriceMultiple);
